# AI16ROM X6711 FEATURE FLAGS

AI16_ENABLE_ASSISTANT := true
AI16_ENABLE_VOICE := true
AI16_ENABLE_VISION := true
AI16_ENABLE_SEARCH := true
AI16_ENABLE_TRANSLATION := true
AI16_ENABLE_OCR := true
AI16_ENABLE_GALLERY_AI := true
AI16_ENABLE_MOVIE_STUDIO := true
AI16_ENABLE_PRIVACY_CENTER := true
AI16_ENABLE_GAME_SPACE := true
AI16_ENABLE_BATTERY_INTELLIGENCE := true
AI16_ENABLE_SMART_CLIPBOARD := true

# Must remain disabled until X6711 HAL validation.
AI16_ENABLE_CAMERA_AI_HDR := false
AI16_ENABLE_CAMERA_AI_NIGHT := false
AI16_ENABLE_CAMERA_RAW := false
AI16_ENABLE_CAMERA_REALTIME_FACE_SWAP := false
AI16_ENABLE_CAMERA_4K60 := false
